import Script from "next/script";
import WhatsAppButton from "@/src/components/ui/whatsapp-button";
import AuthSessionProvider from "../src/providers/session-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import { CartProvider } from "../src/context/cart-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <AuthSessionProvider>

  <CartProvider>

    {children}

    <Toaster
  position="top-center"
  richColors
/>

  </CartProvider>

</AuthSessionProvider>
<Script
  src="https://checkout.razorpay.com/v1/checkout.js"
/>

     <WhatsAppButton />

      </body>
    </html>
  );
}